export const bibleBooks = {
  old: [
    { name: "Genesis", chapters: 50, abbreviation: "Gen" },
    { name: "Exodus", chapters: 40, abbreviation: "Exo" },
    { name: "Leviticus", chapters: 27, abbreviation: "Lev" },
    { name: "Numbers", chapters: 36, abbreviation: "Num" },
    { name: "Deuteronomy", chapters: 34, abbreviation: "Deu" },
    { name: "Joshua", chapters: 24, abbreviation: "Jos" },
    { name: "Judges", chapters: 21, abbreviation: "Jdg" },
    { name: "Ruth", chapters: 4, abbreviation: "Rut" },
    { name: "1 Samuel", chapters: 31, abbreviation: "1Sa" },
    { name: "2 Samuel", chapters: 24, abbreviation: "2Sa" },
    { name: "1 Kings", chapters: 22, abbreviation: "1Ki" },
    { name: "2 Kings", chapters: 25, abbreviation: "2Ki" },
    { name: "1 Chronicles", chapters: 29, abbreviation: "1Ch" },
    { name: "2 Chronicles", chapters: 36, abbreviation: "2Ch" },
    { name: "Ezra", chapters: 10, abbreviation: "Ezr" },
    { name: "Nehemiah", chapters: 13, abbreviation: "Neh" },
    { name: "Esther", chapters: 10, abbreviation: "Est" },
    { name: "Job", chapters: 42, abbreviation: "Job" },
    { name: "Psalms", chapters: 150, abbreviation: "Psa" },
    { name: "Proverbs", chapters: 31, abbreviation: "Pro" },
    { name: "Ecclesiastes", chapters: 12, abbreviation: "Ecc" },
    { name: "Song of Solomon", chapters: 8, abbreviation: "Son" },
    { name: "Isaiah", chapters: 66, abbreviation: "Isa" },
    { name: "Jeremiah", chapters: 52, abbreviation: "Jer" },
    { name: "Lamentations", chapters: 5, abbreviation: "Lam" },
    { name: "Ezekiel", chapters: 48, abbreviation: "Eze" },
    { name: "Daniel", chapters: 12, abbreviation: "Dan" },
    { name: "Hosea", chapters: 14, abbreviation: "Hos" },
    { name: "Joel", chapters: 3, abbreviation: "Joe" },
    { name: "Amos", chapters: 9, abbreviation: "Amo" },
    { name: "Obadiah", chapters: 1, abbreviation: "Oba" },
    { name: "Jonah", chapters: 4, abbreviation: "Jon" },
    { name: "Micah", chapters: 7, abbreviation: "Mic" },
    { name: "Nahum", chapters: 3, abbreviation: "Nah" },
    { name: "Habakkuk", chapters: 3, abbreviation: "Hab" },
    { name: "Zephaniah", chapters: 3, abbreviation: "Zep" },
    { name: "Haggai", chapters: 2, abbreviation: "Hag" },
    { name: "Zechariah", chapters: 14, abbreviation: "Zec" },
    { name: "Malachi", chapters: 4, abbreviation: "Mal" }
  ],
  new: [
    { name: "Matthew", chapters: 28, abbreviation: "Mat" },
    { name: "Mark", chapters: 16, abbreviation: "Mar" },
    { name: "Luke", chapters: 24, abbreviation: "Luk" },
    { name: "John", chapters: 21, abbreviation: "Joh" },
    { name: "Acts", chapters: 28, abbreviation: "Act" },
    { name: "Romans", chapters: 16, abbreviation: "Rom" },
    { name: "1 Corinthians", chapters: 16, abbreviation: "1Co" },
    { name: "2 Corinthians", chapters: 13, abbreviation: "2Co" },
    { name: "Galatians", chapters: 6, abbreviation: "Gal" },
    { name: "Ephesians", chapters: 6, abbreviation: "Eph" },
    { name: "Philippians", chapters: 4, abbreviation: "Phi" },
    { name: "Colossians", chapters: 4, abbreviation: "Col" },
    { name: "1 Thessalonians", chapters: 5, abbreviation: "1Th" },
    { name: "2 Thessalonians", chapters: 3, abbreviation: "2Th" },
    { name: "1 Timothy", chapters: 6, abbreviation: "1Ti" },
    { name: "2 Timothy", chapters: 4, abbreviation: "2Ti" },
    { name: "Titus", chapters: 3, abbreviation: "Tit" },
    { name: "Philemon", chapters: 1, abbreviation: "Phm" },
    { name: "Hebrews", chapters: 13, abbreviation: "Heb" },
    { name: "James", chapters: 5, abbreviation: "Jam" },
    { name: "1 Peter", chapters: 5, abbreviation: "1Pe" },
    { name: "2 Peter", chapters: 3, abbreviation: "2Pe" },
    { name: "1 John", chapters: 5, abbreviation: "1Jo" },
    { name: "2 John", chapters: 1, abbreviation: "2Jo" },
    { name: "3 John", chapters: 1, abbreviation: "3Jo" },
    { name: "Jude", chapters: 1, abbreviation: "Jud" },
    { name: "Revelation", chapters: 22, abbreviation: "Rev" }
  ]
};